env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
plugins:
  - '@typescript-eslint'
rules:
  indent: off
  "@typescript-eslint/indent": 
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  max-len:
    - error
    - 120
  "@typescript-eslint/consistent-type-definitions":
    - off
