image: node:alpine

cache:
  paths:
  - node_modules
  
before_script:
  - yarn

stages:
- deploy

pages:
  stage: deploy
  script:
    - yarn build
    - mv public _public
    - mv build public
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
    - master
