include:
- template: Dependency-Scanning.gitlab-ci.yml
- template: SAST.gitlab-ci.yml
- template: DAST.gitlab-ci.yml

variables:
  DAST_WEBSITE: https://test.adamzielonka.pro

stages:
- build
- test
- deploy
- dast

test:
  image: node:alpine
  stage: test
  script:
    - yarn
    - yarn test
  cache:
    paths:
    - node_modules

build:
  image: node:alpine
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - build
  cache:
    paths:
    - node_modules

pages:
  image: alpine
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  dependencies: ["build"]
  script:
    - mv build public
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
    - master
