image: node:14.9.0-alpine

stages:
- build
- test
- deploy

build:
  stage: build
  script:
    - pnpm install
    - pnpm build
  artifacts:
    expire_in: 1 week
    paths:
      - build
  cache:
    paths:
    - node_modules

test:
  stage: test
  script:
    - pnpm install
    - pnpm test-coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
      junit: junit.xml
  cache:
    paths:
    - node_modules
  needs:
    - build

lint:
  stage: test
  allow_failure: true
  script:
    - pnpm install
    - pnpm lint & pnpm lint-junit
  artifacts:
    reports:
      junit: junit.xml
  cache:
    paths:
    - node_modules
  needs:
    - build

pages:
  image: alpine
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  needs:
    - job: build
      artifacts: true
    - test
  script:
    - mv build public
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
    - master
