image: node:14.9.0-alpine

stages:
- build
- test
- deploy

test:
  stage: test
  script:
    - yarn
    - yarn test-coverage
  cache:
    paths:
    - node_modules

lint:
  stage: test
  allow_failure: true
  script:
    - yarn
    - yarn lint
  cache:
    paths:
    - node_modules

build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - build
  cache:
    paths:
    - node_modules

pages:
  image: alpine
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  needs:
    - job: build
      artifacts: true
    - test
  script:
    - mv build public
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
    - master

include:
  - template: Dependency-Scanning.gitlab-ci.yml
