image: node:14.9.0-alpine

stages:
- build
- test
- deploy

.yarn:
  before_script:
    - yarn
  cache:
    untracked: true
    paths:
      - .yarn/
      - .pnp.js

build:
  extends: .yarn
  stage: build
  script:
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - build

test:
  extends: .yarn
  stage: test
  script:
    - yarn test-coverage
  needs:
    - build

lint:
  extends: .yarn
  stage: test
  allow_failure: true
  script:
    - yarn lint
  needs:
    - build

pages:
  image: alpine
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  needs:
    - job: build
      artifacts: true
    - test
  script:
    - mv build public
  artifacts:
    expire_in: 1 week
    paths:
    - public
  only:
    - master
